
name = "jish-dev"
main = "main.ts"
workers_dev = true
compatibility_date = "2022-11-30"

[site]
bucket = "../remix/public"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = true


[define]
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"
"process.env.NODE_ENV" = '"production"'


[env.dev.site]
bucket = "../remix/public"

[env.dev.define] 
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"
"process.env.NODE_ENV" = '"development"'
