
name = "jish-dev"
main = "entry.worker.ts"

workers_dev = true
kv_namespaces = [
  { binding = "IMAGE_KV", id = "a56d15f6e7ed425fa3bbf0b699dec84e", preview_id = "ae76c3e2edc2414dab8bfdd2764a1874" },
]

compatibility_date = "2022-11-30"

[define]
"process.env.REMIX_DEV_SERVER_WS_PORT" = "8002"

[site]
bucket = "../remix-app/public"

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
fallthrough = true